props.bf_Shank_Dia = 10.0
#props.bf_Pitch = 1.5 # Coarse
props.bf_Pitch = 1.25  # Fine
props.bf_Crest_Percent = 10
props.bf_Root_Percent = 10
props.bf_Major_Dia = 10.0
props.bf_Minor_Dia = props.bf_Major_Dia - (1.082532 * props.bf_Pitch)
props.bf_Hex_Head_Flat_Distance = 17.0
props.bf_Hex_Head_Height = 6.4
props.bf_Cap_Head_Dia = 16.0
props.bf_Cap_Head_Height = 10.0
props.bf_CounterSink_Head_Dia = 20.0
props.bf_Allen_Bit_Flat_Distance = 8.0
props.bf_Allen_Bit_Depth = 5.0
props.bf_Pan_Head_Dia = 20.0
props.bf_Dome_Head_Dia = 20.0
props.bf_Philips_Bit_Dia = props.bf_Pan_Head_Dia * (1.82 / 5.6)
#props.bf_Phillips_Bit_Depth = Get_Phillips_Bit_Height(props.bf_Philips_Bit_Dia)
props.bf_Hex_Nut_Height = 8.0
props.bf_Hex_Nut_Flat_Distance = 17.0
props.bf_Thread_Length = 20
props.bf_Shank_Length = 0.0
